modLoader="javafml"
loaderVersion="[38,)"
license="GNU GPLv3"
[[mods]]
modId="hbde"
version="${file.jarVersion}"
displayName="HotbarDumpingExcess"
logoFile="hbde.png"
credits=" "
authors="frankV"
description='''Dump excess pickup items just in your hotbar!'''
[[dependencies.hbde]]
    modId="forge"
    mandatory=true
    versionRange="[38,)"
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.hbde]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,1.19)"
    ordering="NONE"
    side="BOTH"
